name: Civil Services - City Council Data for Phoenix, AZ
description: This project provides the City Council Data, Headshots & City Photo for Phoenix, AZ ( JSON, XML, CSV, SQL & YML formats )
theme: jekyll-theme-cayman